run:
  timeout: 5m
  tests: true
  skip-dirs:
    - .github
  skip-files:
    - ".*_gen.go$"
output:
  sort-results: true
linters: # https://golangci-lint.run/usage/linters/
  enable-all: true
  disable:
    - depguard
    - forbidigo
    - exhaustruct
    - nlreturn
    - paralleltest
    - testableexamples
    - varnamelen
    - wrapcheck
    - goerr113 # Use errorlint instead.
    - gofmt # Use gofumpt instead.
    - testpackage
    - tparallel # Use paralleltest instead.
    - wsl
    - deadcode  # deprecated
    - exhaustivestruct # deprecated
    - golint      # deprecated
    - ifshort     # deprecated
    - interfacer  # deprecated
    - maligned    # deprecated
    - nosnakecase # deprecated
    - scopelint   # deprecated
    - structcheck # deprecated
    - varcheck    # deprecated
issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - funlen
