version: "2"
run:
  tests: true
linters:
  default: all
  disable:
    - depguard
    - err113
    - exhaustruct
    - forbidigo
    - nlreturn
    - noinlineerr
    - paralleltest
    - testableexamples
    - testpackage
    - tparallel
    - varnamelen
    - wrapcheck
    - wsl
    - wsl_v5
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - funlen
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
      - ^\.github/
      - .*_gen\.go$
formatters:
  enable:
    - gci
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
      - ^\.github/
      - .*_gen\.go$
